<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            /* ================= Cairo ================= */
            ['governorate_id' => 1, 'name' => ['ar' => '15 مايو', 'en' => '15 May']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الازبكية', 'en' => 'Al Azbakeyah']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الاميرية', 'en' => 'Al Amiriyah']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الانفوشى', 'en' => 'Anfoushi']],
            ['governorate_id' => 1, 'name' => ['ar' => 'العباسية', 'en' => 'Abbaseya']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الباشا', 'en' => 'Al Basha']],
            ['governorate_id' => 1, 'name' => ['ar' => 'البساتين', 'en' => 'Al Basatin']],
            ['governorate_id' => 1, 'name' => ['ar' => 'التبين', 'en' => 'Tebin']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الخليفة', 'en' => 'El-Khalifa']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الدراسة', 'en' => 'El darrasa']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الدرب الاحمر', 'en' => 'Aldarb Alahmar']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الزاوية الحمراء', 'en' => 'Zawya al-Hamra']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الزيتون', 'en' => 'El-Zaytoun']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الساحل', 'en' => 'Sahel']],
            ['governorate_id' => 1, 'name' => ['ar' => 'السلام', 'en' => 'El Salam']],
            ['governorate_id' => 1, 'name' => ['ar' => 'السيدة زينب', 'en' => 'Sayeda Zeinab']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الشرابية', 'en' => 'El Sharabeya']],
            ['governorate_id' => 1, 'name' => ['ar' => 'مدينة الشروق', 'en' => 'Shorouk']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الظاهر', 'en' => 'El Daher']],
            ['governorate_id' => 1, 'name' => ['ar' => 'العتبة', 'en' => 'Ataba']],
            ['governorate_id' => 1, 'name' => ['ar' => 'القاهرة الجديدة', 'en' => 'New Cairo']],
            ['governorate_id' => 1, 'name' => ['ar' => 'المرج', 'en' => 'El Marg']],
            ['governorate_id' => 1, 'name' => ['ar' => 'عزبة النخل', 'en' => 'Ezbet el Nakhl']],
            ['governorate_id' => 1, 'name' => ['ar' => 'المطرية', 'en' => 'Matareya']],
            ['governorate_id' => 1, 'name' => ['ar' => 'المعادى', 'en' => 'Maadi']],
            ['governorate_id' => 1, 'name' => ['ar' => 'المعصرة', 'en' => 'Maasara']],
            ['governorate_id' => 1, 'name' => ['ar' => 'المقطم', 'en' => 'Mokattam']],
            ['governorate_id' => 1, 'name' => ['ar' => 'المنيل', 'en' => 'Manyal']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الموسكى', 'en' => 'Mosky']],
            ['governorate_id' => 1, 'name' => ['ar' => 'النزهة', 'en' => 'Nozha']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الوايلى', 'en' => 'Waily']],
            ['governorate_id' => 1, 'name' => ['ar' => 'باب الشعرية', 'en' => 'Bab al-Shereia']],
            ['governorate_id' => 1, 'name' => ['ar' => 'بولاق', 'en' => 'Bolaq']],
            ['governorate_id' => 1, 'name' => ['ar' => 'جاردن سيتى', 'en' => 'Garden City']],
            ['governorate_id' => 1, 'name' => ['ar' => 'حدائق القبة', 'en' => 'Hadayek El-Kobba']],
            ['governorate_id' => 1, 'name' => ['ar' => 'حلوان', 'en' => 'Helwan']],
            ['governorate_id' => 1, 'name' => ['ar' => 'دار السلام', 'en' => 'Dar Al Salam']],
            ['governorate_id' => 1, 'name' => ['ar' => 'شبرا', 'en' => 'Shubra']],
            ['governorate_id' => 1, 'name' => ['ar' => 'طره', 'en' => 'Tura']],
            ['governorate_id' => 1, 'name' => ['ar' => 'عابدين', 'en' => 'Abdeen']],
            ['governorate_id' => 1, 'name' => ['ar' => 'عباسية', 'en' => 'Abaseya']],
            ['governorate_id' => 1, 'name' => ['ar' => 'عين شمس', 'en' => 'Ain Shams']],
            ['governorate_id' => 1, 'name' => ['ar' => 'مدينة نصر', 'en' => 'Nasr City']],
            ['governorate_id' => 1, 'name' => ['ar' => 'مصر الجديدة', 'en' => 'New Heliopolis']],
            ['governorate_id' => 1, 'name' => ['ar' => 'مصر القديمة', 'en' => 'Masr Al Qadima']],
            ['governorate_id' => 1, 'name' => ['ar' => 'منشية ناصر', 'en' => 'Mansheya Nasir']],
            ['governorate_id' => 1, 'name' => ['ar' => 'مدينة بدر', 'en' => 'Badr City']],
            ['governorate_id' => 1, 'name' => ['ar' => 'مدينة العبور', 'en' => 'Obour City']],
            ['governorate_id' => 1, 'name' => ['ar' => 'وسط البلد', 'en' => 'Cairo Downtown']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الزمالك', 'en' => 'Zamalek']],
            ['governorate_id' => 1, 'name' => ['ar' => 'قصر النيل', 'en' => 'Kasr El Nile']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الرحاب', 'en' => 'Rehab']],
            ['governorate_id' => 1, 'name' => ['ar' => 'القطامية', 'en' => 'Katameya']],
            ['governorate_id' => 1, 'name' => ['ar' => 'مدينتي', 'en' => 'Madinty']],
            ['governorate_id' => 1, 'name' => ['ar' => 'روض الفرج', 'en' => 'Rod Alfarag']],
            ['governorate_id' => 1, 'name' => ['ar' => 'شيراتون', 'en' => 'Sheraton']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الجمالية', 'en' => 'El-Gamaleya']],
            ['governorate_id' => 1, 'name' => ['ar' => 'العاشر من رمضان', 'en' => '10th of Ramadan City']],
            ['governorate_id' => 1, 'name' => ['ar' => 'الحلمية', 'en' => 'Helmeyat Alzaytoun']],
            ['governorate_id' => 1, 'name' => ['ar' => 'النزهة الجديدة', 'en' => 'New Nozha']],
            ['governorate_id' => 1, 'name' => ['ar' => 'العاصمة الإدارية', 'en' => 'Capital New']],

            /* ================= Giza ================= */
            ['governorate_id' => 2, 'name' => ['ar' => 'الجيزة', 'en' => 'Giza']],
            ['governorate_id' => 2, 'name' => ['ar' => 'السادس من أكتوبر', 'en' => 'Sixth of October']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الشيخ زايد', 'en' => 'Cheikh Zayed']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الحوامدية', 'en' => 'Hawamdiyah']],
            ['governorate_id' => 2, 'name' => ['ar' => 'البدرشين', 'en' => 'Al Badrasheen']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الصف', 'en' => 'Saf']],
            ['governorate_id' => 2, 'name' => ['ar' => 'أطفيح', 'en' => 'Atfih']],
            ['governorate_id' => 2, 'name' => ['ar' => 'العياط', 'en' => 'Al Ayat']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الباويطي', 'en' => 'Al-Bawaiti']],
            ['governorate_id' => 2, 'name' => ['ar' => 'منشأة القناطر', 'en' => 'Manshiyet Al Qanater']],
            ['governorate_id' => 2, 'name' => ['ar' => 'أوسيم', 'en' => 'Oaseem']],
            ['governorate_id' => 2, 'name' => ['ar' => 'كرداسة', 'en' => 'Kerdasa']],
            ['governorate_id' => 2, 'name' => ['ar' => 'أبو النمرس', 'en' => 'Abu Nomros']],
            ['governorate_id' => 2, 'name' => ['ar' => 'كفر غطاطي', 'en' => 'Kafr Ghati']],
            ['governorate_id' => 2, 'name' => ['ar' => 'منشأة البكاري', 'en' => 'Manshiyet Al Bakari']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الدقى', 'en' => 'Dokki']],
            ['governorate_id' => 2, 'name' => ['ar' => 'العجوزة', 'en' => 'Agouza']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الهرم', 'en' => 'Haram']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الوراق', 'en' => 'Warraq']],
            ['governorate_id' => 2, 'name' => ['ar' => 'امبابة', 'en' => 'Imbaba']],
            ['governorate_id' => 2, 'name' => ['ar' => 'بولاق الدكرور', 'en' => 'Boulaq Dakrour']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الواحات البحرية', 'en' => 'Al Wahat Al Baharia']],
            ['governorate_id' => 2, 'name' => ['ar' => 'العمرانية', 'en' => 'Omraneya']],
            ['governorate_id' => 2, 'name' => ['ar' => 'المنيب', 'en' => 'Moneeb']],
            ['governorate_id' => 2, 'name' => ['ar' => 'بين السرايات', 'en' => 'Bin Alsarayat']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الكيت كات', 'en' => 'Kit Kat']],
            ['governorate_id' => 2, 'name' => ['ar' => 'المهندسين', 'en' => 'Mohandessin']],
            ['governorate_id' => 2, 'name' => ['ar' => 'فيصل', 'en' => 'Faisal']],
            ['governorate_id' => 2, 'name' => ['ar' => 'أبو رواش', 'en' => 'Abu Rawash']],
            ['governorate_id' => 2, 'name' => ['ar' => 'حدائق الأهرام', 'en' => 'Hadayek Alahram']],
            ['governorate_id' => 2, 'name' => ['ar' => 'الحرانية', 'en' => 'Haraneya']],
            ['governorate_id' => 2, 'name' => ['ar' => 'حدائق اكتوبر', 'en' => 'Hadayek October']],
            ['governorate_id' => 2, 'name' => ['ar' => 'صفط اللبن', 'en' => 'Saft Allaban']],
            ['governorate_id' => 2, 'name' => ['ar' => 'القرية الذكية', 'en' => 'Smart Village']],
            ['governorate_id' => 2, 'name' => ['ar' => 'ارض اللواء', 'en' => 'Ard Ellwaa']],

            /* ================= Alexandria ================= */
            ['governorate_id' => 3, 'name' => ['ar' => 'ابو قير', 'en' => 'Abu Qir']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الابراهيمية', 'en' => 'Al Ibrahimeyah']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الأزاريطة', 'en' => 'Azarita']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الانفوشى', 'en' => 'Anfoushi']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الدخيلة', 'en' => 'Dekheila']],
            ['governorate_id' => 3, 'name' => ['ar' => 'السيوف', 'en' => 'El Soyof']],
            ['governorate_id' => 3, 'name' => ['ar' => 'العامرية', 'en' => 'Ameria']],
            ['governorate_id' => 3, 'name' => ['ar' => 'اللبان', 'en' => 'El Labban']],
            ['governorate_id' => 3, 'name' => ['ar' => 'المفروزة', 'en' => 'Al Mafrouza']],
            ['governorate_id' => 3, 'name' => ['ar' => 'المنتزه', 'en' => 'El Montaza']],
            ['governorate_id' => 3, 'name' => ['ar' => 'المنشية', 'en' => 'Mansheya']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الناصرية', 'en' => 'Naseria']],
            ['governorate_id' => 3, 'name' => ['ar' => 'امبروزو', 'en' => 'Ambrozo']],
            ['governorate_id' => 3, 'name' => ['ar' => 'باب شرق', 'en' => 'Bab Sharq']],
            ['governorate_id' => 3, 'name' => ['ar' => 'برج العرب', 'en' => 'Bourj Alarab']],
            ['governorate_id' => 3, 'name' => ['ar' => 'ستانلى', 'en' => 'Stanley']],
            ['governorate_id' => 3, 'name' => ['ar' => 'سموحة', 'en' => 'Smouha']],
            ['governorate_id' => 3, 'name' => ['ar' => 'سيدى بشر', 'en' => 'Sidi Bishr']],
            ['governorate_id' => 3, 'name' => ['ar' => 'شدس', 'en' => 'Shads']],
            ['governorate_id' => 3, 'name' => ['ar' => 'غيط العنب', 'en' => 'Gheet Alenab']],
            ['governorate_id' => 3, 'name' => ['ar' => 'فلمينج', 'en' => 'Fleming']],
            ['governorate_id' => 3, 'name' => ['ar' => 'فيكتوريا', 'en' => 'Victoria']],
            ['governorate_id' => 3, 'name' => ['ar' => 'كامب شيزار', 'en' => 'Camp Shizar']],
            ['governorate_id' => 3, 'name' => ['ar' => 'كرموز', 'en' => 'Karmooz']],
            ['governorate_id' => 3, 'name' => ['ar' => 'محطة الرمل', 'en' => 'Mahta Alraml']],
            ['governorate_id' => 3, 'name' => ['ar' => 'مينا البصل', 'en' => 'Mina El-Basal']],
            ['governorate_id' => 3, 'name' => ['ar' => 'العصافرة', 'en' => 'Asafra']],
            ['governorate_id' => 3, 'name' => ['ar' => 'العجمي', 'en' => 'Agamy']],
            ['governorate_id' => 3, 'name' => ['ar' => 'بكوس', 'en' => 'Bakos']],
            ['governorate_id' => 3, 'name' => ['ar' => 'بولكلي', 'en' => 'Boulkly']],
            ['governorate_id' => 3, 'name' => ['ar' => 'كليوباترا', 'en' => 'Cleopatra']],
            ['governorate_id' => 3, 'name' => ['ar' => 'جليم', 'en' => 'Glim']],
            ['governorate_id' => 3, 'name' => ['ar' => 'المعمورة', 'en' => 'Al Mamurah']],
            ['governorate_id' => 3, 'name' => ['ar' => 'المندرة', 'en' => 'Al Mandara']],
            ['governorate_id' => 3, 'name' => ['ar' => 'محرم بك', 'en' => 'Moharam Bek']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الشاطبي', 'en' => 'Elshatby']],
            ['governorate_id' => 3, 'name' => ['ar' => 'سيدي جابر', 'en' => 'Sidi Gaber']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الساحل الشمالي', 'en' => 'North Coast/sahel']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الحضرة', 'en' => 'Alhadra']],
            ['governorate_id' => 3, 'name' => ['ar' => 'العطارين', 'en' => 'Alattarin']],
            ['governorate_id' => 3, 'name' => ['ar' => 'سيدي كرير', 'en' => 'Sidi Kerir']],
            ['governorate_id' => 3, 'name' => ['ar' => 'الجمرك', 'en' => 'Elgomrok']],
            ['governorate_id' => 3, 'name' => ['ar' => 'المكس', 'en' => 'Al Max']],
            ['governorate_id' => 3, 'name' => ['ar' => 'مارينا', 'en' => 'Marina']],

            /* ================= Dakahlia ================= */
            ['governorate_id' => 4, 'name' => ['ar' => 'المنصورة', 'en' => 'Mansoura']],
            ['governorate_id' => 4, 'name' => ['ar' => 'طلخا', 'en' => 'Talkha']],
            ['governorate_id' => 4, 'name' => ['ar' => 'ميت غمر', 'en' => 'Mitt Ghamr']],
            ['governorate_id' => 4, 'name' => ['ar' => 'دكرنس', 'en' => 'Dekernes']],
            ['governorate_id' => 4, 'name' => ['ar' => 'أجا', 'en' => 'Aga']],
            ['governorate_id' => 4, 'name' => ['ar' => 'منية النصر', 'en' => 'Menia El Nasr']],
            ['governorate_id' => 4, 'name' => ['ar' => 'السنبلاوين', 'en' => 'Sinbillawin']],
            ['governorate_id' => 4, 'name' => ['ar' => 'الكردي', 'en' => 'El Kurdi']],
            ['governorate_id' => 4, 'name' => ['ar' => 'بني عبيد', 'en' => 'Bani Ubaid']],
            ['governorate_id' => 4, 'name' => ['ar' => 'المنزلة', 'en' => 'Al Manzala']],
            ['governorate_id' => 4, 'name' => ['ar' => 'تمي الأمديد', 'en' => "tami al'amdid"]],
            ['governorate_id' => 4, 'name' => ['ar' => 'الجمالية', 'en' => 'aljamalia']],
            ['governorate_id' => 4, 'name' => ['ar' => 'شربين', 'en' => 'Sherbin']],
            ['governorate_id' => 4, 'name' => ['ar' => 'المطرية', 'en' => 'Mataria']],
            ['governorate_id' => 4, 'name' => ['ar' => 'بلقاس', 'en' => 'Belqas']],
            ['governorate_id' => 4, 'name' => ['ar' => 'ميت سلسيل', 'en' => 'Meet Salsil']],
            ['governorate_id' => 4, 'name' => ['ar' => 'جمصة', 'en' => 'Gamasa']],
            ['governorate_id' => 4, 'name' => ['ar' => 'محلة دمنة', 'en' => 'Mahalat Damana']],
            ['governorate_id' => 4, 'name' => ['ar' => 'نبروه', 'en' => 'Nabroh']],

            /* ================= Red Sea ================= */
            ['governorate_id' => 5, 'name' => ['ar' => 'الغردقة', 'en' => 'Hurghada']],
            ['governorate_id' => 5, 'name' => ['ar' => 'رأس غارب', 'en' => 'Ras Ghareb']],
            ['governorate_id' => 5, 'name' => ['ar' => 'سفاجا', 'en' => 'Safaga']],
            ['governorate_id' => 5, 'name' => ['ar' => 'القصير', 'en' => 'El Qusiar']],
            ['governorate_id' => 5, 'name' => ['ar' => 'مرسى علم', 'en' => 'Marsa Alam']],
            ['governorate_id' => 5, 'name' => ['ar' => 'الشلاتين', 'en' => 'Shalatin']],
            ['governorate_id' => 5, 'name' => ['ar' => 'حلايب', 'en' => 'Halaib']],
            ['governorate_id' => 5, 'name' => ['ar' => 'الدهار', 'en' => 'Aldahar']],

            /* ================= Beheira ================= */
            ['governorate_id' => 6, 'name' => ['ar' => 'دمنهور', 'en' => 'Damanhour']],
            ['governorate_id' => 6, 'name' => ['ar' => 'كفر الدوار', 'en' => 'Kafr El Dawar']],
            ['governorate_id' => 6, 'name' => ['ar' => 'رشيد', 'en' => 'Rashid']],
            ['governorate_id' => 6, 'name' => ['ar' => 'إدكو', 'en' => 'Edco']],
            ['governorate_id' => 6, 'name' => ['ar' => 'أبو المطامير', 'en' => 'Abu al-Matamir']],
            ['governorate_id' => 6, 'name' => ['ar' => 'أبو حمص', 'en' => 'Abu Homs']],
            ['governorate_id' => 6, 'name' => ['ar' => 'الدلنجات', 'en' => 'Delengat']],
            ['governorate_id' => 6, 'name' => ['ar' => 'المحمودية', 'en' => 'Mahmoudiyah']],
            ['governorate_id' => 6, 'name' => ['ar' => 'الرحمانية', 'en' => 'Rahmaniyah']],
            ['governorate_id' => 6, 'name' => ['ar' => 'إيتاي البارود', 'en' => 'Itai Baroud']],
            ['governorate_id' => 6, 'name' => ['ar' => 'حوش عيسى', 'en' => 'Housh Eissa']],
            ['governorate_id' => 6, 'name' => ['ar' => 'شبراخيت', 'en' => 'Shubrakhit']],
            ['governorate_id' => 6, 'name' => ['ar' => 'كوم حمادة', 'en' => 'Kom Hamada']],
            ['governorate_id' => 6, 'name' => ['ar' => 'بدر', 'en' => 'Badr']],
            ['governorate_id' => 6, 'name' => ['ar' => 'وادي النطرون', 'en' => 'Wadi Natrun']],
            ['governorate_id' => 6, 'name' => ['ar' => 'النوبارية الجديدة', 'en' => 'New Nubaria']],
            ['governorate_id' => 6, 'name' => ['ar' => 'النوبارية', 'en' => 'Alnoubareya']],

            /* ================= Fayoum ================= */
            ['governorate_id' => 7, 'name' => ['ar' => 'الفيوم', 'en' => 'Fayoum']],
            ['governorate_id' => 7, 'name' => ['ar' => 'الفيوم الجديدة', 'en' => 'Fayoum El Gedida']],
            ['governorate_id' => 7, 'name' => ['ar' => 'طامية', 'en' => 'Tamiya']],
            ['governorate_id' => 7, 'name' => ['ar' => 'سنورس', 'en' => 'Snores']],
            ['governorate_id' => 7, 'name' => ['ar' => 'إطسا', 'en' => 'Etsa']],
            ['governorate_id' => 7, 'name' => ['ar' => 'إبشواي', 'en' => 'Epschway']],
            ['governorate_id' => 7, 'name' => ['ar' => 'يوسف الصديق', 'en' => 'Yusuf El Sediaq']],
            ['governorate_id' => 7, 'name' => ['ar' => 'الحادقة', 'en' => 'Hadqa']],
            ['governorate_id' => 7, 'name' => ['ar' => 'اطسا', 'en' => 'Atsa']],
            ['governorate_id' => 7, 'name' => ['ar' => 'الجامعة', 'en' => 'Algamaa']],
            ['governorate_id' => 7, 'name' => ['ar' => 'السيالة', 'en' => 'Sayala']],

            /* ================= Gharbia ================= */
            ['governorate_id' => 8, 'name' => ['ar' => 'طنطا', 'en' => 'Tanta']],
            ['governorate_id' => 8, 'name' => ['ar' => 'المحلة الكبرى', 'en' => 'Al Mahalla Al Kobra']],
            ['governorate_id' => 8, 'name' => ['ar' => 'كفر الزيات', 'en' => 'Kafr El Zayat']],
            ['governorate_id' => 8, 'name' => ['ar' => 'زفتى', 'en' => 'Zefta']],
            ['governorate_id' => 8, 'name' => ['ar' => 'السنطة', 'en' => 'El Santa']],
            ['governorate_id' => 8, 'name' => ['ar' => 'قطور', 'en' => 'Qutour']],
            ['governorate_id' => 8, 'name' => ['ar' => 'بسيون', 'en' => 'Basion']],
            ['governorate_id' => 8, 'name' => ['ar' => 'سمنود', 'en' => 'Samannoud']],

            /* ================= Ismailia ================= */
            ['governorate_id' => 9, 'name' => ['ar' => 'الإسماعيلية', 'en' => 'Ismailia']],
            ['governorate_id' => 9, 'name' => ['ar' => 'فايد', 'en' => 'Fayed']],
            ['governorate_id' => 9, 'name' => ['ar' => 'القنطرة شرق', 'en' => 'Qantara Sharq']],
            ['governorate_id' => 9, 'name' => ['ar' => 'القنطرة غرب', 'en' => 'Qantara Gharb']],
            ['governorate_id' => 9, 'name' => ['ar' => 'التل الكبير', 'en' => 'El Tal El Kabier']],
            ['governorate_id' => 9, 'name' => ['ar' => 'أبو صوير', 'en' => 'Abu Sawir']],
            ['governorate_id' => 9, 'name' => ['ar' => 'القصاصين الجديدة', 'en' => 'Kasasien El Gedida']],
            ['governorate_id' => 9, 'name' => ['ar' => 'نفيشة', 'en' => 'Nefesha']],
            ['governorate_id' => 9, 'name' => ['ar' => 'الشيخ زايد', 'en' => 'Sheikh Zayed']],

            /* ================= Monufya ================= */
            ['governorate_id' => 10, 'name' => ['ar' => 'شبين الكوم', 'en' => 'Shbeen El Koom']],
            ['governorate_id' => 10, 'name' => ['ar' => 'مدينة السادات', 'en' => 'Sadat City']],
            ['governorate_id' => 10, 'name' => ['ar' => 'منوف', 'en' => 'Menouf']],
            ['governorate_id' => 10, 'name' => ['ar' => 'سرس الليان', 'en' => 'Sars El-Layan']],
            ['governorate_id' => 10, 'name' => ['ar' => 'أشمون', 'en' => 'Ashmon']],
            ['governorate_id' => 10, 'name' => ['ar' => 'الباجور', 'en' => 'Al Bagor']],
            ['governorate_id' => 10, 'name' => ['ar' => 'قويسنا', 'en' => 'Quesna']],
            ['governorate_id' => 10, 'name' => ['ar' => 'بركة السبع', 'en' => 'Berkat El Saba']],
            ['governorate_id' => 10, 'name' => ['ar' => 'تلا', 'en' => 'Tala']],
            ['governorate_id' => 10, 'name' => ['ar' => 'الشهداء', 'en' => 'Al Shohada']],

            /* ================= Minya ================= */
            ['governorate_id' => 11, 'name' => ['ar' => 'المنيا', 'en' => 'Minya']],
            ['governorate_id' => 11, 'name' => ['ar' => 'المنيا الجديدة', 'en' => 'Minya El Gedida']],
            ['governorate_id' => 11, 'name' => ['ar' => 'العدوة', 'en' => 'El Adwa']],
            ['governorate_id' => 11, 'name' => ['ar' => 'مغاغة', 'en' => 'Magagha']],
            ['governorate_id' => 11, 'name' => ['ar' => 'بني مزار', 'en' => 'Bani Mazar']],
            ['governorate_id' => 11, 'name' => ['ar' => 'مطاي', 'en' => 'Mattay']],
            ['governorate_id' => 11, 'name' => ['ar' => 'سمالوط', 'en' => 'Samalut']],
            ['governorate_id' => 11, 'name' => ['ar' => 'المدينة الفكرية', 'en' => 'Madinat El Fekria']],
            ['governorate_id' => 11, 'name' => ['ar' => 'ملوي', 'en' => 'Meloy']],
            ['governorate_id' => 11, 'name' => ['ar' => 'دير مواس', 'en' => 'Deir Mawas']],
            ['governorate_id' => 11, 'name' => ['ar' => 'ابو قرقاص', 'en' => 'Abu Qurqas']],
            ['governorate_id' => 11, 'name' => ['ar' => 'ارض سلطان', 'en' => 'Ard Sultan']],

            /* ================= Qalubia ================= */
            ['governorate_id' => 12, 'name' => ['ar' => 'بنها', 'en' => 'Banha']],
            ['governorate_id' => 12, 'name' => ['ar' => 'قليوب', 'en' => 'Qalyub']],
            ['governorate_id' => 12, 'name' => ['ar' => 'شبرا الخيمة', 'en' => 'Shubra Al Khaimah']],
            ['governorate_id' => 12, 'name' => ['ar' => 'القناطر الخيرية', 'en' => 'Al Qanater Charity']],
            ['governorate_id' => 12, 'name' => ['ar' => 'الخانكة', 'en' => 'Khanka']],
            ['governorate_id' => 12, 'name' => ['ar' => 'كفر شكر', 'en' => 'Kafr Shukr']],
            ['governorate_id' => 12, 'name' => ['ar' => 'طوخ', 'en' => 'Tukh']],
            ['governorate_id' => 12, 'name' => ['ar' => 'قها', 'en' => 'Qaha']],
            ['governorate_id' => 12, 'name' => ['ar' => 'العبور', 'en' => 'Obour']],
            ['governorate_id' => 12, 'name' => ['ar' => 'الخصوص', 'en' => 'Khosous']],
            ['governorate_id' => 12, 'name' => ['ar' => 'شبين القناطر', 'en' => 'Shibin Al Qanater']],
            ['governorate_id' => 12, 'name' => ['ar' => 'مسطرد', 'en' => 'Mostorod']],

            /* ================= New Valley ================= */
            ['governorate_id' => 13, 'name' => ['ar' => 'الخارجة', 'en' => 'El Kharga']],
            ['governorate_id' => 13, 'name' => ['ar' => 'باريس', 'en' => 'Paris']],
            ['governorate_id' => 13, 'name' => ['ar' => 'موط', 'en' => 'Mout']],
            ['governorate_id' => 13, 'name' => ['ar' => 'الفرافرة', 'en' => 'Farafra']],
            ['governorate_id' => 13, 'name' => ['ar' => 'بلاط', 'en' => 'Balat']],
            ['governorate_id' => 13, 'name' => ['ar' => 'الداخلة', 'en' => 'Dakhla']],

            /* ================= South Sinai ================= */
            ['governorate_id' => 14, 'name' => ['ar' => 'السويس', 'en' => 'Suez']],
            ['governorate_id' => 14, 'name' => ['ar' => 'الجناين', 'en' => 'Alganayen']],
            ['governorate_id' => 14, 'name' => ['ar' => 'عتاقة', 'en' => 'Ataqah']],
            ['governorate_id' => 14, 'name' => ['ar' => 'العين السخنة', 'en' => 'Ain Sokhna']],
            ['governorate_id' => 14, 'name' => ['ar' => 'فيصل', 'en' => 'Faysal']],

            /* ================= Aswan ================= */
            ['governorate_id' => 15, 'name' => ['ar' => 'أسوان', 'en' => 'Aswan']],
            ['governorate_id' => 15, 'name' => ['ar' => 'أسوان الجديدة', 'en' => 'Aswan El Gedida']],
            ['governorate_id' => 15, 'name' => ['ar' => 'دراو', 'en' => 'Drau']],
            ['governorate_id' => 15, 'name' => ['ar' => 'كوم أمبو', 'en' => 'Kom Ombo']],
            ['governorate_id' => 15, 'name' => ['ar' => 'نصر النوبة', 'en' => 'Nasr Al Nuba']],
            ['governorate_id' => 15, 'name' => ['ar' => 'كلابشة', 'en' => 'Kalabsha']],
            ['governorate_id' => 15, 'name' => ['ar' => 'إدفو', 'en' => 'Edfu']],
            ['governorate_id' => 15, 'name' => ['ar' => 'الرديسية', 'en' => 'Al-Radisiyah']],
            ['governorate_id' => 15, 'name' => ['ar' => 'البصيلية', 'en' => 'Al Basilia']],
            ['governorate_id' => 15, 'name' => ['ar' => 'السباعية', 'en' => 'Al Sibaeia']],
            ['governorate_id' => 15, 'name' => ['ar' => 'ابوسمبل السياحية', 'en' => 'Abo Simbl Al Siyahia']],
            ['governorate_id' => 15, 'name' => ['ar' => 'مرسى علم', 'en' => 'Marsa Alam']],

            /* ================= Assiut ================= */
            ['governorate_id' => 16, 'name' => ['ar' => 'أسيوط', 'en' => 'Assiut']],
            ['governorate_id' => 16, 'name' => ['ar' => 'أسيوط الجديدة', 'en' => 'Assiut El Gedida']],
            ['governorate_id' => 16, 'name' => ['ar' => 'ديروط', 'en' => 'Dayrout']],
            ['governorate_id' => 16, 'name' => ['ar' => 'منفلوط', 'en' => 'Manfalut']],
            ['governorate_id' => 16, 'name' => ['ar' => 'القوصية', 'en' => 'Qusiya']],
            ['governorate_id' => 16, 'name' => ['ar' => 'أبنوب', 'en' => 'Abnoub']],
            ['governorate_id' => 16, 'name' => ['ar' => 'أبو تيج', 'en' => 'Abu Tig']],
            ['governorate_id' => 16, 'name' => ['ar' => 'الغنايم', 'en' => 'El Ghanaim']],
            ['governorate_id' => 16, 'name' => ['ar' => 'ساحل سليم', 'en' => 'Sahel Selim']],
            ['governorate_id' => 16, 'name' => ['ar' => 'البداري', 'en' => 'El Badari']],
            ['governorate_id' => 16, 'name' => ['ar' => 'صدفا', 'en' => 'Sidfa']],

            /* ================= Bani Sweif ================= */
            ['governorate_id' => 17, 'name' => ['ar' => 'بني سويف', 'en' => 'Bani Sweif']],
            ['governorate_id' => 17, 'name' => ['ar' => 'بني سويف الجديدة', 'en' => 'Beni Suef El Gedida']],
            ['governorate_id' => 17, 'name' => ['ar' => 'الواسطى', 'en' => 'Al Wasta']],
            ['governorate_id' => 17, 'name' => ['ar' => 'ناصر', 'en' => 'Naser']],
            ['governorate_id' => 17, 'name' => ['ar' => 'إهناسيا', 'en' => 'Ehnasia']],
            ['governorate_id' => 17, 'name' => ['ar' => 'ببا', 'en' => 'beba']],
            ['governorate_id' => 17, 'name' => ['ar' => 'الفشن', 'en' => 'Fashn']],
            ['governorate_id' => 17, 'name' => ['ar' => 'سمسطا', 'en' => 'Somasta']],
            ['governorate_id' => 17, 'name' => ['ar' => 'الاباصيرى', 'en' => 'Alabbaseri']],
            ['governorate_id' => 17, 'name' => ['ar' => 'مقبل', 'en' => 'Mokbel']],

            /* ================= PorSaid ================= */
            ['governorate_id' => 18, 'name' => ['ar' => 'بورسعيد', 'en' => 'PorSaid']],
            ['governorate_id' => 18, 'name' => ['ar' => 'بورفؤاد', 'en' => 'Port Fouad']],
            ['governorate_id' => 18, 'name' => ['ar' => 'العرب', 'en' => 'Alarab']],
            ['governorate_id' => 18, 'name' => ['ar' => 'حى الزهور', 'en' => 'Zohour']],
            ['governorate_id' => 18, 'name' => ['ar' => 'حى الشرق', 'en' => 'Alsharq']],
            ['governorate_id' => 18, 'name' => ['ar' => 'حى الضواحى', 'en' => 'Aldawahi']],
            ['governorate_id' => 18, 'name' => ['ar' => 'حى المناخ', 'en' => 'Almanakh']],
            ['governorate_id' => 18, 'name' => ['ar' => 'حى مبارك', 'en' => 'Mubarak']],

            /* ================= Damietta ================= */
            ['governorate_id' => 19, 'name' => ['ar' => 'دمياط', 'en' => 'Damietta']],
            ['governorate_id' => 19, 'name' => ['ar' => 'دمياط الجديدة', 'en' => 'New Damietta']],
            ['governorate_id' => 19, 'name' => ['ar' => 'رأس البر', 'en' => 'Ras El Bar']],
            ['governorate_id' => 19, 'name' => ['ar' => 'فارسكور', 'en' => 'Faraskour']],
            ['governorate_id' => 19, 'name' => ['ar' => 'الزرقا', 'en' => 'Zarqa']],
            ['governorate_id' => 19, 'name' => ['ar' => 'السرو', 'en' => 'alsaru']],
            ['governorate_id' => 19, 'name' => ['ar' => 'الروضة', 'en' => 'alruwda']],
            ['governorate_id' => 19, 'name' => ['ar' => 'كفر البطيخ', 'en' => 'Kafr El-Batikh']],
            ['governorate_id' => 19, 'name' => ['ar' => 'عزبة البرج', 'en' => 'Azbet Al Burg']],
            ['governorate_id' => 19, 'name' => ['ar' => 'ميت أبو غالب', 'en' => 'Meet Abou Ghalib']],
            ['governorate_id' => 19, 'name' => ['ar' => 'كفر سعد', 'en' => 'Kafr Saad']],

            /* ================= Sharqia ================= */
            ['governorate_id' => 20, 'name' => ['ar' => 'الزقازيق', 'en' => 'Zagazig']],
            ['governorate_id' => 20, 'name' => ['ar' => 'العاشر من رمضان', 'en' => 'Al Ashr Men Ramadan']],
            ['governorate_id' => 20, 'name' => ['ar' => 'منيا القمح', 'en' => 'Minya Al Qamh']],
            ['governorate_id' => 20, 'name' => ['ar' => 'بلبيس', 'en' => 'Belbeis']],
            ['governorate_id' => 20, 'name' => ['ar' => 'مشتول السوق', 'en' => 'Mashtoul El Souq']],
            ['governorate_id' => 20, 'name' => ['ar' => 'القنايات', 'en' => 'Qenaiat']],
            ['governorate_id' => 20, 'name' => ['ar' => 'أبو حماد', 'en' => 'Abu Hammad']],
            ['governorate_id' => 20, 'name' => ['ar' => 'القرين', 'en' => 'El Qurain']],
            ['governorate_id' => 20, 'name' => ['ar' => 'ههيا', 'en' => 'Hehia']],
            ['governorate_id' => 20, 'name' => ['ar' => 'أبو كبير', 'en' => 'Abu Kabir']],
            ['governorate_id' => 20, 'name' => ['ar' => 'فاقوس', 'en' => 'Faccus']],
            ['governorate_id' => 20, 'name' => ['ar' => 'الصالحية الجديدة', 'en' => 'El Salihia El Gedida']],
            ['governorate_id' => 20, 'name' => ['ar' => 'الإبراهيمية', 'en' => 'Al Ibrahimiyah']],
            ['governorate_id' => 20, 'name' => ['ar' => 'ديرب نجم', 'en' => 'Deirb Negm']],
            ['governorate_id' => 20, 'name' => ['ar' => 'كفر صقر', 'en' => 'Kafr Saqr']],
            ['governorate_id' => 20, 'name' => ['ar' => 'أولاد صقر', 'en' => 'Awlad Saqr']],
            ['governorate_id' => 20, 'name' => ['ar' => 'الحسينية', 'en' => 'Husseiniya']],
            ['governorate_id' => 20, 'name' => ['ar' => 'صان الحجر القبلية', 'en' => 'san alhajar alqablia']],
            ['governorate_id' => 20, 'name' => ['ar' => 'منشأة أبو عمر', 'en' => 'Manshayat Abu Omar']],

            /* ================= South Sinai ================= */
            ['governorate_id' => 21, 'name' => ['ar' => 'الطور', 'en' => 'Al Toor']],
            ['governorate_id' => 21, 'name' => ['ar' => 'شرم الشيخ', 'en' => 'Sharm El-Shaikh']],
            ['governorate_id' => 21, 'name' => ['ar' => 'دهب', 'en' => 'Dahab']],
            ['governorate_id' => 21, 'name' => ['ar' => 'نويبع', 'en' => 'Nuweiba']],
            ['governorate_id' => 21, 'name' => ['ar' => 'طابا', 'en' => 'Taba']],
            ['governorate_id' => 21, 'name' => ['ar' => 'سانت كاترين', 'en' => 'Saint Catherine']],
            ['governorate_id' => 21, 'name' => ['ar' => 'أبو رديس', 'en' => 'Abu Redis']],
            ['governorate_id' => 21, 'name' => ['ar' => 'أبو زنيمة', 'en' => 'Abu Zenaima']],
            ['governorate_id' => 21, 'name' => ['ar' => 'رأس سدر', 'en' => 'Ras Sidr']],

            /* ================= Kafr El Sheikh ================= */
            ['governorate_id' => 22, 'name' => ['ar' => 'كفر الشيخ', 'en' => 'Kafr El Sheikh']],
            ['governorate_id' => 22, 'name' => ['ar' => 'وسط البلد كفر الشيخ', 'en' => 'Kafr El Sheikh Downtown']],
            ['governorate_id' => 22, 'name' => ['ar' => 'دسوق', 'en' => 'Desouq']],
            ['governorate_id' => 22, 'name' => ['ar' => 'فوه', 'en' => 'Fooh']],
            ['governorate_id' => 22, 'name' => ['ar' => 'مطوبس', 'en' => 'Metobas']],
            ['governorate_id' => 22, 'name' => ['ar' => 'برج البرلس', 'en' => 'Burg Al Burullus']],
            ['governorate_id' => 22, 'name' => ['ar' => 'بلطيم', 'en' => 'Baltim']],
            ['governorate_id' => 22, 'name' => ['ar' => 'سيدي سالم', 'en' => 'Sidi Salim']],
            ['governorate_id' => 22, 'name' => ['ar' => 'الحامول', 'en' => 'Hamol']],
            ['governorate_id' => 22, 'name' => ['ar' => 'بيلا', 'en' => 'Bela']],
            ['governorate_id' => 22, 'name' => ['ar' => 'قلين', 'en' => 'Qaleen']],
            ['governorate_id' => 22, 'name' => ['ar' => 'سيدي غازي', 'en' => 'Sidi Ghazi']],

            /* ================= Matrouh ================= */
            ['governorate_id' => 23, 'name' => ['ar' => 'الاسكندرية', 'en' => 'Alexandria']],
            ['governorate_id' => 23, 'name' => ['ar' => 'مرسى مطروح', 'en' => 'Marsa Matrouh']],
            ['governorate_id' => 23, 'name' => ['ar' => 'الضبعة', 'en' => 'Dabaa']],
            ['governorate_id' => 23, 'name' => ['ar' => 'الحمام', 'en' => 'El Hammam']],
            ['governorate_id' => 23, 'name' => ['ar' => 'سيدي براني', 'en' => 'Sidi Barani']],
            ['governorate_id' => 23, 'name' => ['ar' => 'النجيلة', 'en' => 'El Negaila']],
            ['governorate_id' => 23, 'name' => ['ar' => 'سيوة', 'en' => 'Siwa']],
            ['governorate_id' => 23, 'name' => ['ar' => 'مرسى مطروح الجديدة', 'en' => 'New Marsa Matrouh']],

            /* ================= Luxor ================= */
            ['governorate_id' => 24, 'name' => ['ar' => 'الأقصر', 'en' => 'Luxor']],
            ['governorate_id' => 24, 'name' => ['ar' => 'الأقصر الجديدة', 'en' => 'New Luxor']],
            ['governorate_id' => 24, 'name' => ['ar' => 'إسنا', 'en' => 'Esna']],
            ['governorate_id' => 24, 'name' => ['ar' => 'طيبة الجديدة', 'en' => 'New Taiba']],
            ['governorate_id' => 24, 'name' => ['ar' => 'الزينية', 'en' => 'Al Zeniya']],
            ['governorate_id' => 24, 'name' => ['ar' => 'البياضية', 'en' => 'Al Bayadiya']],
            ['governorate_id' => 24, 'name' => ['ar' => 'الكرنك', 'en' => 'Karnak']],

            /* ================= Qena ================= */
            ['governorate_id' => 25, 'name' => ['ar' => 'قنا', 'en' => 'Qena']],
            ['governorate_id' => 25, 'name' => ['ar' => 'قنا الجديدة', 'en' => 'New Qena']],
            ['governorate_id' => 25, 'name' => ['ar' => 'نجع حمادي', 'en' => 'Nag Hammadi']],
            ['governorate_id' => 25, 'name' => ['ar' => 'دشنا', 'en' => 'Deshna']],
            ['governorate_id' => 25, 'name' => ['ar' => 'قفط', 'en' => 'Qift']],
            ['governorate_id' => 25, 'name' => ['ar' => 'الوقف', 'en' => 'Al Waqf']],
            ['governorate_id' => 25, 'name' => ['ar' => 'أبو تشت', 'en' => 'Abu Tesht']],
            ['governorate_id' => 25, 'name' => ['ar' => 'نقادة', 'en' => 'Nagada']],
            ['governorate_id' => 25, 'name' => ['ar' => 'الشفا', 'en' => 'Al Shafa']],

            /* ================= Sohag ================= */
            ['governorate_id' => 26, 'name' => ['ar' => 'سوهاج', 'en' => 'Sohag']],
            ['governorate_id' => 26, 'name' => ['ar' => 'سوهاج الجديدة', 'en' => 'New Sohag']],
            ['governorate_id' => 26, 'name' => ['ar' => 'أخميم', 'en' => 'Akhmeem']],
            ['governorate_id' => 26, 'name' => ['ar' => 'المراغة', 'en' => 'Al Maragha']],
            ['governorate_id' => 26, 'name' => ['ar' => 'البلينا', 'en' => 'Al Balina']],
            ['governorate_id' => 26, 'name' => ['ar' => 'جهينة', 'en' => 'Juhayna']],
            ['governorate_id' => 26, 'name' => ['ar' => 'طما', 'en' => 'Tama']],
            ['governorate_id' => 26, 'name' => ['ar' => 'أبو تيج', 'en' => 'Abu Tig']],
            ['governorate_id' => 26, 'name' => ['ar' => 'ساقلته', 'en' => 'Saqlatah']],
            ['governorate_id' => 26, 'name' => ['ar' => 'دار السلام', 'en' => 'Dar El Salam']],
            ['governorate_id' => 26, 'name' => ['ar' => 'طهطا', 'en' => 'Tahta']],
            ['governorate_id' => 26, 'name' => ['ar' => 'أخميم', 'en' => 'Akhmeem']],
        ];

        $insertData = [];
        foreach ($cities as $city) {
           $insertData[] = [
               'governorate_id' => $city['governorate_id'],
               'name' => json_encode($city['name'], JSON_UNESCAPED_UNICODE),
               'created_at' => now(),
               'updated_at' => now(),
           ];
        }


        DB::table('cities')->insert($insertData);
    }
}
